--- 
abstract: Generate automatic documentation of DBIx::Class::Schema objects
author: 
  - Jason Kohles, <email@jasonkohles.com>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBICx-AutoDoc
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Grouped: 0
  Class::Inspector: 0
  DBIx::Class: 0
  Data::Dump: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Template: 0
version: 0.03
